### ISSUE TITLE
Version number epoch is lower than backports

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-redis#11]
Backports has epoch `3:`, Dotdeb has `2:`
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

Could we go 3?

```
$ apt-cache policy redis-server
redis-server:
  Installed: 2:3.2.5-1~dotdeb+8.1
  Candidate: 2:3.2.6-1~dotdeb+8.1
  Version table:
     3:3.2.5-4~bpo8+1 0
        100 http://debian-archive.trafficmanager.net/debian/ jessie-backports/main amd64 Packages
     2:3.2.6-1~dotdeb+8.1 0
        500 http://packages.dotdeb.org/ jessie/all amd64 Packages
 *** 2:3.2.5-1~dotdeb+8.1 0
        500 http://packages.dotdeb.org/ jessie/all amd64 Packages
        100 /var/lib/dpkg/status
     2:3.2.4-1~dotdeb+8.1 0
        500 http://packages.dotdeb.org/ jessie/all amd64 Packages
```

**Comment by szepeviktor** [comment]
>   * Bump epoch as the "2" prefix makes it look like we are shipping version 2.x
>    of Redis itself.

http://metadata.ftp-master.debian.org/changelogs/main/r/redis/redis_3.2.5-4~bpo8+1_changelog

**Comment by gplessis** [comment]
I'm sorry but Dotdeb will discontinue its support for Redis packages:
* I will keep releasing Redis 3.2 packages for a seamless transition
* but I won't release any Redis 4.0+ packages

You should now migrate to official backports, even if you're using Redis 3.2. See #10 for more details.
