### ISSUE TITLE
Stretch support

### ISSUE THREAD

**Issue by myazaki** [gplessis/dotdeb-redis#14]
Hi, is Stretch support on the plan?

**Comment by gplessis** [comment]
Redis 3.2 is already available for Stretch and @lamby is working on providing 4.0+ in stretch-backports, so Dotdeb won't publish any Redis packages for this distribution, sorry.

* [Debian packages of Redis](http://packages.debian.org/redis-server)
* Issue #10 about Dotdeb discontinuing Redis packages

**Comment by lamby** [comment]
Latest 4.x will hit stretch-backports very soon and will be kept up to date for at least the life of stretch.
