### ISSUE TITLE
redis-sentinel symlink exists in 2 packages

### ISSUE THREAD

**Issue by verwilst** [gplessis/dotdeb-redis#5]
Both redis-server and redis-sentinel packages create a symlink to /usr/bin/redis-sentinel, which makes installing redis-sentinel impossible on at least Jessie.

Unpacking redis-sentinel (2:3.0.2-1~dotdeb+8.1) ...dpkg: error processing archive /var/cache/apt/archives/redis-sentinel_2%3a3.0.2-1~dotdeb+8.1_amd64.deb (--unpack): trying to overwrite '/usr/bin/redis-sentinel', which is also in package redis-server 2:3.0.2-1~dotdeb+8.1

**Comment by gplessis** [comment]
It has been fixed with the 3.0.3 packages.
